import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Achievement Targetter", // Título de la página
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <link rel="icon" href="/crosshair.png" type="image/png" sizes="32x32" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-300 antialiased flex flex-col items-center justify-center min-h-screen`}
      >
        <Header />
        <div className="max-w-xl w-full bg-gray-300 p-4 bg-background text-foreground"> {/* Contenedor centrado */}
          {children}
        </div>
      </body>
    </html>
  );
}
